name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: ArtemShatalin/buildozer-action@v1.6.1
        with:
          command: buildozer android debug
          buildozer_version: mastername: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: ArtemShatalin/buildozer-action@v1.6.1
        with:
          command: buildozer android debug
          buildozer_version: master
